<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\japanese_restaurant.glb --transform
Author: annzep (https://sketchfab.com/annzep)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-restaurant-9b3c5076541148fca229edeb1a1b07ef
Title: Japanese Restaurant
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('models/japanese_restaurant-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Mesh
			geometry={gltf.nodes.polySurface113_lambert1_0.geometry}
			material={gltf.materials.lambert1}
			position={[0, 0, -1.55]}
		/>
		<T.Group position={[0, 0.27, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface513_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface514_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface515_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface516_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface517_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface518_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface519_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface520_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface521_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface522_lambert40_0.geometry}
				material={gltf.materials.lambert40}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface523_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface524_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface525_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
		</T.Group>
		<T.Group position={[8.52, 0, -11.33]} rotation={[-Math.PI, 0, -Math.PI]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface526_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface527_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface528_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface529_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface530_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface531_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface532_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface533_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface534_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface535_lambert40_0.geometry}
				material={gltf.materials.lambert40}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface536_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface537_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface538_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
		</T.Group>
		<T.Group position={[-0.02, 0, -6.31]} rotation={[-Math.PI, 0, -Math.PI]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface652_lambert4_0.geometry}
				material={gltf.materials.lambert4}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface653_phong6_0.geometry}
				material={gltf.materials.phong6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface654_phong6_0.geometry}
				material={gltf.materials.phong6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface655_lambert4_0.geometry}
				material={gltf.materials.lambert4}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface656_lambert4_0.geometry}
				material={gltf.materials.lambert4}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface657_phong6_0.geometry}
				material={gltf.materials.phong6}
			/>
		</T.Group>
		<T.Group position={[-0.07, 0, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface99_lambert4_0.geometry}
				material={gltf.materials.lambert4}
				position={[-0.05, -0.01, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface100_lambert12_0.geometry}
				material={gltf.materials.lambert12}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface101_lambert4_0.geometry}
				material={gltf.materials.lambert4}
				position={[0.07, -0.02, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface102_lambert12_0.geometry}
				material={gltf.materials.lambert12}
			/>
		</T.Group>
		<T.Group
			position={[1.65, 8.54, 2.48]}
			rotation={[1.45, 0, Math.PI / 2]}
			scale={[0.59, 1.27, 2.3]}
		>
			<T.Mesh
				geometry={gltf.nodes.pCube140_lambert32_0.geometry}
				material={gltf.materials.lambert32}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube140_lambert33_0.geometry}
				material={gltf.materials.lambert33}
			/>
		</T.Group>
		<T.Group position={[0.12, 8.56, 2.59]} rotation={[-0.12, 0, 0]} scale={[4.64, 1.78, 0.03]}>
			<T.Mesh
				geometry={gltf.nodes.pCube154_lambert11_0.geometry}
				material={gltf.materials.lambert11}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube154_lambert10_0.geometry}
				material={gltf.materials.lambert1}
			/>
		</T.Group>
		<T.Group position={[-6.98, 8.49, 3.53]} scale={[0.04, 0.89, 1.05]}>
			<T.Mesh
				geometry={gltf.nodes.pCube155_lambert14_0.geometry}
				material={gltf.materials.lambert1}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube155_lambert15_0.geometry}
				material={gltf.materials.lambert15}
			/>
		</T.Group>
		<T.Group position={[-1.64, 3.38, 2.53]} rotation={[0, Math.PI / 2, 0]} scale={[0.22, 1, 1.19]}>
			<T.Mesh
				geometry={gltf.nodes.pCube159_lambert12_0.geometry}
				material={gltf.materials.lambert12}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube159_lambert13_0.geometry}
				material={gltf.materials.lambert13}
			/>
		</T.Group>
		<T.Group position={[-0.01, 0.92, 0.03]} rotation={[0.06, 0, 0.1]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface260_lambert16_0.geometry}
				material={gltf.materials.lambert16}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface260_lambert17_0.geometry}
				material={gltf.materials.lambert17}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface261_lambert16_0.geometry}
				material={gltf.materials.lambert16}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface262_lambert16_0.geometry}
				material={gltf.materials.lambert16}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface263_lambert16_0.geometry}
				material={gltf.materials.lambert16}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface264_lambert36_0.geometry}
				material={gltf.materials.lambert36}
			/>
		</T.Group>
		<T.Group position={[0, 0, -0.2]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface255_lambert7_0.geometry}
				material={gltf.materials.lambert7}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface255_phong1_0.geometry}
				material={gltf.materials.phong1}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface255_lambert6_0.geometry}
				material={gltf.materials.lambert6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface255_lambert5_0.geometry}
				material={gltf.materials.lambert5}
			/>
		</T.Group>
		<T.Group position={[0, 0, -0.04]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface259_lambert7_0.geometry}
				material={gltf.materials.lambert7}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface259_phong1_0.geometry}
				material={gltf.materials.phong1}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface259_lambert6_0.geometry}
				material={gltf.materials.lambert6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface259_lambert5_0.geometry}
				material={gltf.materials.lambert5}
			/>
		</T.Group>
		<T.Group
			position={[-7.34, 8.49, 3.53]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.04, 0.89, 1.05]}
		>
			<T.Mesh
				geometry={gltf.nodes.pCube205_lambert14_0.geometry}
				material={gltf.materials.lambert1}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube205_lambert15_0.geometry}
				material={gltf.materials.lambert15}
			/>
		</T.Group>
		<T.Group position={[0, 0, -0.26]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface497_lambert36_0.geometry}
				material={gltf.materials.lambert36}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface498_lambert8_0.geometry}
				material={gltf.materials.lambert8}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface498_lambert9_0.geometry}
				material={gltf.materials.lambert9}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface499_lambert9_0.geometry}
				material={gltf.materials.lambert9}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface500_lambert9_0.geometry}
				material={gltf.materials.lambert9}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface501_lambert9_0.geometry}
				material={gltf.materials.lambert9}
			/>
		</T.Group>
		<T.Group position={[2.11, -0.02, 11.63]} rotation={[-0.5, 1.31, 0.39]} scale={0.6}>
			<T.Mesh
				geometry={gltf.nodes.polySurface434_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface435_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface436_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface437_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface438_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface439_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface440_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface441_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface442_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
		</T.Group>
		<T.Group position={[4.12, 0.5, 11.77]} rotation={[-0.1, 1.42, -0.04]} scale={[0.6, 0.59, 0.6]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface395_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-6.36, -3.19, -2.23]}
				scale={1.6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface396_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-6.3, -3.18, -2.14]}
				scale={1.6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface397_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-6.44, -3.21, -2.3]}
				scale={1.6}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface398_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface399_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface400_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface401_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface402_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface403_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
		</T.Group>
		<T.Group position={[11.99, -0.52, 9.44]} rotation={[-3.12, 0.27, 3.1]} scale={[0.6, 0.61, 0.6]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface425_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-4.61, -2.31, -1.62]}
				scale={1.43}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface426_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-4.57, -2.31, -1.55]}
				scale={1.43}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface427_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[-4.67, -2.32, -1.67]}
				scale={1.43}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface428_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface429_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface430_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface431_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface432_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface433_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
		</T.Group>
		<T.Group position={[5.3, -0.72, -1.3]} rotation={[-0.34, -0.97, -0.3]} scale={0.65}>
			<T.Mesh
				geometry={gltf.nodes.polySurface404_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface405_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface406_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface407_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface408_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface409_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface410_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface411_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface412_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
		</T.Group>
		<T.Group position={[-13.12, 0, 11.15]} rotation={[-Math.PI, 0, -Math.PI]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface339_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface340_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface341_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface342_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[2.24, -1.09, -1.95]}
				scale={1.36}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface343_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[2.22, -1.08, -1.92]}
				scale={1.36}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface344_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[2.25, -1.1, -1.99]}
				scale={1.36}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface345_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface346_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface347_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface348_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface349_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface350_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface351_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface352_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface353_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface354_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface355_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface356_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface357_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface358_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface359_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface360_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface361_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface362_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface363_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface364_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface365_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface366_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface367_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface368_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface369_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface370_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface371_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface372_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface373_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface374_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface375_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface376_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface377_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface378_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[6.15, -2.32, -4.53]}
				scale={1.82}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface379_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[6.23, -2.31, -4.56]}
				scale={1.82}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface380_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[6.13, -2.34, -4.47]}
				scale={1.82}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface381_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface382_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface383_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface384_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface385_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface386_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface387_lambert20_0.geometry}
				material={gltf.materials.lambert20}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface387_lambert21_0.geometry}
				material={gltf.materials.lambert21}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface388_lambert19_0.geometry}
				material={gltf.materials.lambert19}
				position={[0.38, 2.25, -0.21]}
			/>
		</T.Group>
		<T.Group position={[-15.44, 0, 7.36]} rotation={[-Math.PI, 0, -Math.PI]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface286_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.9, -2.47, -2.79]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface287_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.86, -2.48, -2.76]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface288_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.8, -2.49, -2.7]}
				scale={1.65}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface289_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface290_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface291_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface292_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface293_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface294_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface295_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface296_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface297_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface298_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface299_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface300_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface301_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface302_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface303_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface304_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface305_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface306_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface307_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface308_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface309_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface310_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface311_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface312_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface313_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface314_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface315_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface316_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface317_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface318_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface319_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface320_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface321_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface322_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface323_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface324_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface325_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.43, -1.65, -1.55]}
				scale={1.58}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface326_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.45, -1.64, -1.49]}
				scale={1.58}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface327_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[4.39, -1.66, -1.6]}
				scale={1.58}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface328_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface329_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface330_lambert18_0.geometry}
				material={gltf.materials.lambert18}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface331_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface332_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface333_lambert19_0.geometry}
				material={gltf.materials.lambert19}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface334_lambert20_0.geometry}
				material={gltf.materials.lambert20}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface334_lambert21_0.geometry}
				material={gltf.materials.lambert21}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface335_lambert19_0.geometry}
				material={gltf.materials.lambert19}
				position={[0.11, 2.29, 0.13]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface336_lambert19_0.geometry}
				material={gltf.materials.lambert19}
				position={[0.11, 2.29, 0.13]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface337_lambert19_0.geometry}
				material={gltf.materials.lambert19}
				position={[-0.03, 2.16, -0.08]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface338_lambert19_0.geometry}
				material={gltf.materials.lambert19}
				position={[0.08, 0.84, 0.14]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface389_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[1.13, 2.43, 3.72]}
				rotation={[0, -0.44, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface390_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[1.13, 2.43, 3.72]}
				rotation={[0, -0.44, 0]}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface391_lambert18_0.geometry}
				material={gltf.materials.lambert18}
				position={[1.13, 2.43, 3.72]}
				rotation={[0, -0.44, 0]}
			/>
		</T.Group>
		<T.Group position={[5.39, 2.87, 0.93]} rotation={[0.23, 0, 0]} scale={[0.51, 0.51, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube236_lambert23_0.geometry}
				material={gltf.materials.lambert23}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube236_lambert25_0.geometry}
				material={gltf.materials.lambert25}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube236_lambert24_0.geometry}
				material={gltf.materials.lambert24}
			/>
		</T.Group>
		<T.Group position={[4.62, 2.82, 1.15]} rotation={[0.23, 0, 0]} scale={[0.51, 0.51, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube237_lambert23_0.geometry}
				material={gltf.materials.lambert23}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube237_lambert25_0.geometry}
				material={gltf.materials.lambert25}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube237_lambert24_0.geometry}
				material={gltf.materials.lambert24}
			/>
		</T.Group>
		<T.Group position={[3.76, 2.82, 1.15]} rotation={[0.23, 0, 0]} scale={[0.51, 0.51, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube238_lambert23_0.geometry}
				material={gltf.materials.lambert23}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube238_lambert25_0.geometry}
				material={gltf.materials.lambert25}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube238_lambert24_0.geometry}
				material={gltf.materials.lambert24}
			/>
		</T.Group>
		<T.Group position={[2.99, 2.86, 1]} rotation={[0.23, 0, 0]} scale={[0.51, 0.51, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube239_lambert23_0.geometry}
				material={gltf.materials.lambert23}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube239_lambert25_0.geometry}
				material={gltf.materials.lambert25}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube239_lambert24_0.geometry}
				material={gltf.materials.lambert24}
			/>
		</T.Group>
		<T.Group position={[2.3, 2.79, 1.27]} rotation={[0.23, 0, 0]} scale={[0.51, 0.51, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube240_lambert23_0.geometry}
				material={gltf.materials.lambert23}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube240_lambert25_0.geometry}
				material={gltf.materials.lambert25}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube240_lambert24_0.geometry}
				material={gltf.materials.lambert24}
			/>
		</T.Group>
		<T.Group position={[-0.19, 3.93, -2.84]} rotation={[0.24, 0, 0]} scale={0.56}>
			<T.Mesh
				geometry={gltf.nodes.pCube244_lambert26_0.geometry}
				material={gltf.materials.lambert26}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube244_lambert27_0.geometry}
				material={gltf.materials.lambert27}
			/>
		</T.Group>
		<T.Group position={[-1.58, 3.93, -2.83]} rotation={[0.24, 0.12, 0]} scale={[0.58, 0.56, 0.58]}>
			<T.Mesh
				geometry={gltf.nodes.pCube245_lambert26_0.geometry}
				material={gltf.materials.lambert26}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube245_lambert27_0.geometry}
				material={gltf.materials.lambert27}
			/>
		</T.Group>
		<T.Group position={[-1.31, 4.29, -4.27]} rotation={[0.24, 0.07, 0]} scale={[0.62, 0.56, 0.62]}>
			<T.Mesh
				geometry={gltf.nodes.pCube246_lambert26_0.geometry}
				material={gltf.materials.lambert26}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube246_lambert27_0.geometry}
				material={gltf.materials.lambert27}
			/>
		</T.Group>
		<T.Group position={[0.47, 4.01, -3.16]} rotation={[0.24, -0.16, 0]} scale={[0.49, 0.56, 0.49]}>
			<T.Mesh
				geometry={gltf.nodes.pCube247_lambert26_0.geometry}
				material={gltf.materials.lambert26}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube247_lambert27_0.geometry}
				material={gltf.materials.lambert27}
			/>
		</T.Group>
		<T.Group position={[-0.52, 4.39, -3.23]} rotation={[0.24, 0, 0]} scale={0.56}>
			<T.Mesh
				geometry={gltf.nodes.pCube248_lambert26_0.geometry}
				material={gltf.materials.lambert26}
			/>
			<T.Mesh
				geometry={gltf.nodes.pCube248_lambert27_0.geometry}
				material={gltf.materials.lambert27}
			/>
		</T.Group>
		<T.Group position={[0, 0.02, -0.13]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface473_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface474_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface475_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface476_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface477_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface478_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
		</T.Group>
		<T.Group position={[0.31, 0, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface467_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface468_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface469_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface470_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface471_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface472_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
		</T.Group>
		<T.Group position={[0.68, 0.02, -0.24]} rotation={[0, -0.09, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface461_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface462_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface463_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface464_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface465_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface466_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
		</T.Group>
		<T.Group position={[-0.32, 0.02, -0.04]} rotation={[0, 0.07, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface485_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface486_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface487_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface488_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface489_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface490_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
		</T.Group>
		<T.Group position={[-0.22, 0.1, 0.2]} rotation={[0, 0.09, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface479_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface480_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface481_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface482_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface483_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface484_lambert29_0.geometry}
				material={gltf.materials.lambert29}
			/>
		</T.Group>
		<T.Group position={[0.27, 0.09, -0.15]} rotation={[0, -0.07, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface455_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface456_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface457_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface458_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface459_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface460_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
		</T.Group>
		<T.Group position={[-0.37, 0.02, -0.01]} rotation={[0, -0.02, 0]}>
			<T.Mesh
				geometry={gltf.nodes.polySurface491_lambert28_0.geometry}
				material={gltf.materials.lambert28}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface492_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface493_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface494_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface495_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
			<T.Mesh
				geometry={gltf.nodes.polySurface496_lambert30_0.geometry}
				material={gltf.materials.lambert30}
			/>
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.pCube1_lambert35_0.geometry}
			material={gltf.materials.lambert35}
			position={[0, 0, -0.6]}
			scale={[10.36, 0.33, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube3_lambert12_0.geometry}
			material={gltf.materials.lambert12}
			position={[0, 8.08, -0.66]}
			rotation={[0.38, 0, 0]}
			scale={[12.08, 0.01, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder1_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[0, 11.8, -3.16]}
			rotation={[0, 0, -Math.PI / 2]}
			scale={[0.2, 0.22, 0.2]}
		/>
		<T.Mesh geometry={gltf.nodes.pCube5_lambert12_0.geometry} material={gltf.materials.lambert12} />
		<T.Mesh
			geometry={gltf.nodes.pCube4_lambert31_0.geometry}
			material={gltf.materials.lambert31}
			position={[0, 7.13, -3.19]}
			scale={[9.13, 1, 3.92]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube121_lambert12_0.geometry}
			material={gltf.materials.lambert12}
			position={[0, 0, -6.4]}
			rotation={[-Math.PI, 0, Math.PI]}
			scale={[-1, 1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder13_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-7.2, 11.76, 3.56]}
			rotation={[Math.PI, 1.52, Math.PI / 2]}
			scale={[0.19, 0.05, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube19_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[-0.09, -0.07, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube42_lambert31_0.geometry}
			material={gltf.materials.lambert31}
			position={[-1.94, 0.64, -1.44]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube44_lambert32_0.geometry}
			material={gltf.materials.lambert32}
			position={[2.15, 0.29, 1.95]}
			rotation={[0, Math.PI / 2, 0]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube45_lambert34_0.geometry}
			material={gltf.materials.lambert34}
			position={[2.15, 2.24, 2.24]}
			rotation={[-Math.PI / 2, Math.PI / 2, 0]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube47_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[0.38, 3.22, 2.05]}
			rotation={[-Math.PI / 2, Math.PI / 2, 0]}
			scale={[10.31, 1, 15.54]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube48_lambert3_0.geometry}
			material={gltf.materials.lambert3}
			position={[-1.26, 3.22, 2.16]}
			rotation={[0, -0.02, -Math.PI / 2]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube49_lambert44_0.geometry}
			material={gltf.materials.lambert44}
			position={[3.09, 2.47, 2.02]}
			rotation={[-1.34, Math.PI / 2, 0]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube50_lambert32_0.geometry}
			material={gltf.materials.lambert32}
			position={[-0.63, 2.48, 2.02]}
			rotation={[-1.34, Math.PI / 2, 0]}
			scale={[10.31, 1, 7.46]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder7_lambert36_0.geometry}
			material={gltf.materials.lambert36}
			position={[-7.13, 1.07, 3.54]}
			scale={0.11}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube51_lambert32_0.geometry}
			material={gltf.materials.lambert32}
			position={[-7.16, 8.36, 3.53]}
			scale={[1, 1, 1.32]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube52_lambert31_0.geometry}
			material={gltf.materials.lambert31}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube53_lambert31_0.geometry}
			material={gltf.materials.lambert31}
			position={[0, 6.92, -0.6]}
			scale={[10.36, 0.33, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube83_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube62_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube10_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube84_lambert32_0.geometry}
			material={gltf.materials.lambert32}
			position={[5.6, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube85_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[5.51, -0.07, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube87_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[-5.58, 6.91, 2.63]}
			scale={[0.23, 0.08, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube88_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[4.57, 6.81, 1.72]}
			rotation={[0, Math.PI / 2, 0]}
			scale={[0.23, 0.12, 22.21]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube89_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[4.57, 6.81, 0.76]}
			rotation={[0, Math.PI / 2, 0]}
			scale={[0.23, 0.12, 22.21]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube90_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[4.57, 6.81, -0.07]}
			rotation={[0, Math.PI / 2, 0]}
			scale={[0.23, 0.12, 22.21]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube91_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[-2.47, 6.91, 2.91]}
			scale={[0.23, 0.08, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube92_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[0.49, 6.91, 2.81]}
			scale={[0.23, 0.08, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube93_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[5.65, 6.91, 2.86]}
			scale={[0.23, 0.08, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube94_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[3.12, 6.91, 2.73]}
			scale={[0.23, 0.08, 10.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube95_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[0.47, 8.39, -1.84]}
			rotation={[0.38, 0, 0]}
			scale={[0.17, 0.01, 9.76]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube96_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[3.14, 8.39, -1.84]}
			rotation={[0.38, 0, 0]}
			scale={[0.17, 0.01, 9.76]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube97_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[5.67, 8.39, -1.84]}
			rotation={[0.38, 0, 0]}
			scale={[0.17, 0.01, 9.76]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube98_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[-2.46, 8.39, -1.84]}
			rotation={[0.38, 0, 0]}
			scale={[0.17, 0.01, 9.76]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube99_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[-5.6, 8.39, -1.84]}
			rotation={[0.38, 0, 0]}
			scale={[0.17, 0.01, 9.76]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube106_lambert33_0.geometry}
			material={gltf.materials.lambert33}
			position={[4.57, 6.81, -1.08]}
			rotation={[0, Math.PI / 2, 0]}
			scale={[0.23, 0.12, 22.21]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube111_lambert33_0.geometry}
			material={gltf.materials.lambert33}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube112_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface53_lambert33_0.geometry}
			material={gltf.materials.lambert33}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface64_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-0.29, -0.3, -3.1]}
			rotation={[Math.PI / 10, 0, 0]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface65_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-6.26, -0.47, -2.59]}
			rotation={[Math.PI / 10, 0, 0]}
			scale={[1.01, 1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface77_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-12.11, -0.42, -2.73]}
			rotation={[Math.PI / 10, 0, 0]}
			scale={[1, 1, 1.08]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface78_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-0.29, -0.68, -2.82]}
			rotation={[0.16, 0, 0]}
			scale={[1, 1, 1.14]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface79_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-6.26, -0.36, -3.55]}
			rotation={[0.23, 0, 0]}
			scale={[1.01, 1, 1.35]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface80_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-12.11, -0.76, -2.32]}
			rotation={[0.16, 0, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface81_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-0.29, -0.6, -2.6]}
			rotation={[0.16, 0, 0]}
			scale={[1, 1, 0.7]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface82_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-6.26, -0.6, -3.03]}
			rotation={[0.14, 0, 0]}
			scale={[1.01, 1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface83_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-12.11, -0.39, -3.35]}
			rotation={[0.21, 0, 0]}
			scale={[1, 1, 0.81]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface84_phong6_0.geometry}
			material={gltf.materials.phong6}
			position={[-0.29, 0.23, -4.89]}
			rotation={[0.3, 0, 0]}
			scale={[1, 1, 0.82]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface85_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-6.26, 0.26, -5.01]}
			rotation={[0.3, 0, 0]}
			scale={[1.01, 1, 0.93]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface86_lambert4_0.geometry}
			material={gltf.materials.lambert4}
			position={[-12.11, 0.25, -4.97]}
			rotation={[0.3, 0, 0]}
			scale={[1, 1, 0.82]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface646_phong6_0.geometry}
			material={gltf.materials.phong6}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface647_lambert4_0.geometry}
			material={gltf.materials.lambert4}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface648_phong6_0.geometry}
			material={gltf.materials.phong6}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface649_lambert4_0.geometry}
			material={gltf.materials.lambert4}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface650_phong6_0.geometry}
			material={gltf.materials.phong6}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface651_lambert4_0.geometry}
			material={gltf.materials.lambert4}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder14_lambert1_0.geometry}
			material={gltf.materials.lambert1}
			position={[-7.14, 11.63, 4.12]}
			scale={[0.03, 0, 0.03]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder15_lambert1_0.geometry}
			material={gltf.materials.lambert1}
			position={[-7.14, 11.63, 2.98]}
			scale={[0.03, 0, 0.03]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube141_lambert12_0.geometry}
			material={gltf.materials.lambert12}
			position={[2, 8.37, 1.61]}
			rotation={[0.93, 0, 0]}
			scale={[0.38, 1.88, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube142_lambert12_0.geometry}
			material={gltf.materials.lambert12}
			position={[-1.66, 8.37, 1.61]}
			rotation={[0.93, 0, 0]}
			scale={[0.38, 1.88, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube143_lambert37_0.geometry}
			material={gltf.materials.lambert37}
			position={[-4.08, 6.26, 1.32]}
			scale={[3.61, 1, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface502_lambert40_0.geometry}
			material={gltf.materials.lambert40}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface503_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface504_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface505_phong5_0.geometry}
			material={gltf.materials.phong5}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface506_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface507_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface508_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface509_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface510_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface511_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface512_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube153_lambert38_0.geometry}
			material={gltf.materials.lambert38}
			position={[0, 1.36, -0.06]}
			scale={[1, 0.8, 1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface539_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface540_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface541_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface542_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface543_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface544_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface545_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface546_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface547_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface548_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface549_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface550_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface551_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface552_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface553_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface554_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface555_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface556_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface557_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface558_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface559_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface560_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface561_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface562_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface563_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface564_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface565_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface566_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface567_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface568_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface569_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface570_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface571_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface572_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface573_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface574_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface575_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface576_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface577_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface578_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface579_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface580_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface581_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface582_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface583_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface584_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface585_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface586_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface587_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface588_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface589_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface590_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface591_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface592_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface593_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface594_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface595_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface596_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface597_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface598_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface599_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface600_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface601_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface602_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface603_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface604_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface605_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface606_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface607_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface608_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface609_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface610_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface611_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface612_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface613_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface614_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface615_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface616_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface617_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface618_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface619_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface620_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface621_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface622_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface623_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface624_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface625_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface626_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface627_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface628_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface629_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface630_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface631_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface632_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface633_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface634_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface635_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface636_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface637_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface638_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface639_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface640_lambert42_0.geometry}
			material={gltf.materials.lambert42}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface641_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface642_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface643_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface644_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface645_lambert41_0.geometry}
			material={gltf.materials.lambert41}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube204_lambert12_0.geometry}
			material={gltf.materials.lambert12}
			position={[2.46, 0, -0.92]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface240_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[0.43, 3.07, -2.84]}
			rotation={[Math.PI / 2, 0, 0]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface241_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[-0.68, 3.16, 8.12]}
			rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface242_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[-0.64, 3.07, 2.29]}
			rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface243_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[-0.68, 3.07, -3.56]}
			rotation={[Math.PI / 2, 0, -Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface244_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[-12.8, 3.24, -2.84]}
			rotation={[Math.PI / 2, 0, 0]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface245_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[0.56, 3.17, -4.12]}
			rotation={[Math.PI / 2, 0, Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface246_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[0.59, 3.07, 1.73]}
			rotation={[Math.PI / 2, 0, Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface247_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[0.59, 3.07, -9.95]}
			rotation={[Math.PI / 2, 0, Math.PI / 2]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface248_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[-0.48, 3.1, 1.07]}
			rotation={[Math.PI / 2, 0, -Math.PI]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface249_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[5.32, 3.07, 1.07]}
			rotation={[Math.PI / 2, 0, -Math.PI]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface250_phong4_0.geometry}
			material={gltf.materials.phong4}
			position={[11.16, 3.11, 1.07]}
			rotation={[Math.PI / 2, 0, -Math.PI]}
			scale={[1, 1, 1.18]}
		/>
		<T.Mesh geometry={gltf.nodes.pCylinder39_phong1_0.geometry} material={gltf.materials.phong1} />
		<T.Mesh
			geometry={gltf.nodes.pCylinder39_lambert6_0.geometry}
			material={gltf.materials.lambert6}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder39_lambert5_0.geometry}
			material={gltf.materials.lambert5}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder39_lambert7_0.geometry}
			material={gltf.materials.lambert7}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface257_lambert7_0.geometry}
			material={gltf.materials.lambert7}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface257_phong1_0.geometry}
			material={gltf.materials.phong1}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface257_lambert6_0.geometry}
			material={gltf.materials.lambert6}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface257_lambert5_0.geometry}
			material={gltf.materials.lambert5}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface258_lambert7_0.geometry}
			material={gltf.materials.lambert7}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface258_phong1_0.geometry}
			material={gltf.materials.phong1}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface258_lambert6_0.geometry}
			material={gltf.materials.lambert6}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface258_lambert5_0.geometry}
			material={gltf.materials.lambert5}
		/>
		<T.Mesh geometry={gltf.nodes.pDisc1_lambert1_0.geometry} material={gltf.materials.lambert1} />
		<T.Mesh
			geometry={gltf.nodes.pCube214_lambert20_0.geometry}
			material={gltf.materials.lambert20}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube214_lambert21_0.geometry}
			material={gltf.materials.lambert21}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface413_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[-3.91, -2.1, -3.02]}
			scale={1.55}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface414_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[-3.88, -2.11, -2.96]}
			scale={1.55}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface415_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[-3.83, -2.11, -2.91]}
			scale={1.55}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface416_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface417_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface418_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface419_lambert19_0.geometry}
			material={gltf.materials.lambert19}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface420_lambert19_0.geometry}
			material={gltf.materials.lambert19}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface421_lambert19_0.geometry}
			material={gltf.materials.lambert19}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface422_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface423_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface424_lambert18_0.geometry}
			material={gltf.materials.lambert18}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface284_lambert19_0.geometry}
			material={gltf.materials.lambert19}
			position={[0.21, 3.35, -0.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.polySurface393_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[6.81, -3.84, -4.85]}
			scale={1.83}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube230_lambert22_0.geometry}
			material={gltf.materials.lambert22}
			position={[5.98, 6.3, 4.94]}
			rotation={[1.92, -0.3, -0.24]}
			scale={0.12}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder46_phong2_0.geometry}
			material={gltf.materials.phong2}
			position={[8.13, 3.13, 1.27]}
			rotation={[0, 0, -0.03]}
			scale={0.46}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder49_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[7.04, 6.76, 2.4]}
			rotation={[-0.63, -1.25, -0.76]}
			scale={0.03}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCylinder50_lambert18_0.geometry}
			material={gltf.materials.lambert18}
			position={[6.85, 6.98, 2.43]}
			rotation={[-0.05, -0.87, -0.12]}
			scale={0.03}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube231_lambert22_0.geometry}
			material={gltf.materials.lambert22}
			position={[7.4, 7.47, 3.35]}
			rotation={[-0.6, -1.27, -1.94]}
			scale={0.11}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube232_lambert39_0.geometry}
			material={gltf.materials.lambert39}
			position={[5.6, 6.46, 4.71]}
			rotation={[1.52, -0.19, -0.34]}
			scale={0.15}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube233_lambert22_0.geometry}
			material={gltf.materials.lambert22}
			position={[6.71, 7.48, 3.76]}
			rotation={[0.91, -0.5, -0.8]}
			scale={0.11}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube234_lambert39_0.geometry}
			material={gltf.materials.lambert39}
			position={[5.88, 6.65, 4]}
			rotation={[1.07, 0.16, -0.61]}
			scale={0.14}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube235_lambert32_0.geometry}
			material={gltf.materials.lambert32}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube249_phong3_0.geometry}
			material={gltf.materials.phong3}
			position={[1.98, 9.24, -1.2]}
			scale={[1.37, 1, 0.02]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube250_phong3_0.geometry}
			material={gltf.materials.phong3}
			position={[3.66, 9.24, -1.2]}
			scale={[1.37, 1, 0.02]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube251_phong3_0.geometry}
			material={gltf.materials.phong3}
			position={[-1.94, 9.24, -1.2]}
			scale={[1.37, 1, 0.02]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube252_phong3_0.geometry}
			material={gltf.materials.phong3}
			position={[-3.63, 9.24, -1.2]}
			scale={[1.37, 1, 0.02]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pasted__polySurface1549_pasted__phong17_0.geometry}
			material={gltf.materials.pasted__phong17}
			position={[-2.04, -2.66, -1.58]}
			rotation={[0, -0.28, 0]}
		/>
		<T.Mesh
			geometry={gltf.nodes.pCube253_lambert43_0.geometry}
			material={gltf.materials.lambert43}
			position={[-0.77, -3.16, 0.73]}
			scale={[1, 0.8, 1]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
