<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 japanese_tea_shop.glb --transform --shadows -p 5
Author: libblekibble (https://sketchfab.com/libblekibble)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/japanese-tea-shop-b7c5d071f3dc46b596aef6914c86bbfe
Title: Japanese Tea Shop
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('models/japanese_tea_shop-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group scale={0.01}>
			<T.Group position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube001_Roof_Tiles_0.geometry}
					material={gltf.materials.Roof_Tiles}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube001_Building_0.geometry}
					material={gltf.materials.Building}
				/>
			</T.Group>
			<T.Group position={[0, 100, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={100}>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube003_Roof_Tiles_0.geometry}
					material={gltf.materials.Roof_Tiles}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube003_Building_0.geometry}
					material={gltf.materials.Building}
				/>
			</T.Group>
			<T.Group
				position={[107.86063, 112.39679, -0.58678]}
				rotation={[-Math.PI / 2, 0, Math.PI / 2]}
				scale={[100, 93.89064, 100]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube004_Roof_Tiles_0.geometry}
					material={gltf.materials.Roof_Tiles}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube004_Building_0.geometry}
					material={gltf.materials.Building}
				/>
			</T.Group>
			<T.Group
				position={[-88.11723, 4.55899, -5.89637]}
				rotation={[-Math.PI / 2, 0, Math.PI / 2]}
				scale={37.61544}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Brown_0.geometry}
					material={gltf.materials.Brown}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material001_0.geometry}
					material={gltf.materials['Material.001']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material003_0.geometry}
					material={gltf.materials['Material.003']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material006_0.geometry}
					material={gltf.materials['Material.006']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material007_0.geometry}
					material={gltf.materials['Material.007']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material005_0.geometry}
					material={gltf.materials['Material.005']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube011_Material008_0.geometry}
					material={gltf.materials['Material.008']}
				/>
			</T.Group>
			<T.Group
				position={[-9.06877, 41.23616, -68.73844]}
				rotation={[-Math.PI / 2, 0, -0.23489]}
				scale={7.66542}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle002_Brown_0.geometry}
					material={gltf.materials.Brown}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle002_Material005_0.geometry}
					material={gltf.materials['Material.005']}
				/>
			</T.Group>
			<T.Group
				position={[69.27415, 37.86345, -68.78348]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={4.25253}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cylinder_Orange_0.geometry}
					material={gltf.materials.Orange}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cylinder_Roof_Tiles_0.geometry}
					material={gltf.materials.Roof_Tiles}
				/>
			</T.Group>
			<T.Group
				position={[57.13785, 15.57362, -72.79142]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[5.7978, 3.05043, 7.39943]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube005_Material015_0.geometry}
					material={gltf.materials['Material.015']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube005_Building_0.geometry}
					material={gltf.materials.Building}
				/>
			</T.Group>
			<!--* GROUND -->
			<T.Group position={[0, -30.27551, 0]} rotation={[-Math.PI / 2, 0, 0]} scale={210.49983}>
				<!-- <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube006_Brown001_0.geometry}
          material={gltf.materials['Brown.001']}
        />
        <T.Mesh
          castShadow
          receiveShadow
          geometry={gltf.nodes.Cube006_Material016_0.geometry}
          material={gltf.materials['Material.016']}
        /> -->
			</T.Group>
			<T.Group
				position={[-51.21304, 73.63002, -66.3167]}
				rotation={[-Math.PI / 2, 0, -0.27225]}
				scale={1.9777}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube030_Material004_0.geometry}
					material={gltf.materials['Material.004']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube030_Material019_0.geometry}
					material={gltf.materials['Material.019']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube030_Material002_0.geometry}
					material={gltf.materials['Material.002']}
				/>
			</T.Group>
			<T.Group
				position={[91.76988, 20.53048, 95.80752]}
				rotation={[-Math.PI / 2, 0, 0.21136]}
				scale={2.7143}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube013_Material004_0.geometry}
					material={gltf.materials['Material.004']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube013_Material019_0.geometry}
					material={gltf.materials['Material.019']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube013_Material002_0.geometry}
					material={gltf.materials['Material.002']}
				/>
			</T.Group>
			<T.Group
				position={[-73.74909, -10.18333, 164.9059]}
				rotation={[-Math.PI / 2, 0, 0.21136]}
				scale={[3.86275, 3.86275, 7.82666]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube014_DarkGreen_0.geometry}
					material={gltf.materials.DarkGreen}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube014_Orange_0.geometry}
					material={gltf.materials.Orange}
				/>
			</T.Group>
			<T.Group
				position={[121.92836, 0.29864, 38.8512]}
				rotation={[-Math.PI / 2, 0, -2.49695]}
				scale={[11.93124, 11.93124, 18.52992]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle007_Material005_0.geometry}
					material={gltf.materials['Material.005']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle007_Orange_0.geometry}
					material={gltf.materials.Orange}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle007_Brown_0.geometry}
					material={gltf.materials.Brown}
				/>
			</T.Group>
			<T.Group
				position={[102.00095, -17.69724, 137.78613]}
				rotation={[-Math.PI / 2, 0, 0.21136]}
				scale={[5.86004, 5.86004, 6.16826]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube012_Material022_0.geometry}
					material={gltf.materials['Material.022']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube012_Material021_0.geometry}
					material={gltf.materials['Material.021']}
				/>
			</T.Group>
			<T.Group
				position={[80.55402, -22.8335, 135.59131]}
				rotation={[-Math.PI / 2, 0, 0.7372]}
				scale={1.2331}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube017_Material004_0.geometry}
					material={gltf.materials['Material.004']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube017_Material019_0.geometry}
					material={gltf.materials['Material.019']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube017_Material002_0.geometry}
					material={gltf.materials['Material.002']}
				/>
			</T.Group>
			<T.Group
				position={[124.80642, -22.55569, 134.36287]}
				rotation={[-Math.PI / 2, 0, -2.82061]}
				scale={[4.00008, 4.00008, 4.21047]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube018_Material024_0.geometry}
					material={gltf.materials['Material.024']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube018_Material023_0.geometry}
					material={gltf.materials['Material.023']}
				/>
			</T.Group>
			<T.Group
				position={[122.67414, 18.74418, 95.10152]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[8.55857, 8.55857, 10.01749]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube019_Brown_0.geometry}
					material={gltf.materials.Brown}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube019_Emmission_0.geometry}
					material={gltf.materials.Emmission}
				/>
			</T.Group>
			<T.Group
				position={[57.30376, 44.64159, -68.7277]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={3.55511}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Plane009_Material027_0.geometry}
					material={gltf.materials['Material.027']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Plane009_Material026_0.geometry}
					material={gltf.materials['Material.026']}
				/>
			</T.Group>
			<T.Group
				position={[-86.42241, 43.57826, 55.03395]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[1.90716, 1.90716, 3.36059]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Plane008_Material002_0.geometry}
					material={gltf.materials['Material.002']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Plane008_Material025_0.geometry}
					material={gltf.materials['Material.025']}
				/>
			</T.Group>
			<T.Group
				position={[16.65537, 49.0559, -69.4498]}
				rotation={[-Math.PI / 2, 0, -2.24276]}
				scale={[4.00008, 4.00008, 4.21047]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube021_Material024_0.geometry}
					material={gltf.materials['Material.024']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube021_Material023_0.geometry}
					material={gltf.materials['Material.023']}
				/>
			</T.Group>
			<T.Group
				position={[-71.25769, 63.11811, -68.63155]}
				rotation={[-Math.PI / 2, 0, 1.00369]}
				scale={76.23937}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube022_Material005_0.geometry}
					material={gltf.materials['Material.005']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube022_Material003_0.geometry}
					material={gltf.materials['Material.003']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube022_Material007_0.geometry}
					material={gltf.materials['Material.007']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Cube022_Material006_0.geometry}
					material={gltf.materials['Material.006']}
				/>
			</T.Group>
			<T.Group
				position={[105.42905, -0.58692, -76.24859]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[6.6989, 6.6989, 13.97332]}
			>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle019_Black_0.geometry}
					material={gltf.materials.Black}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle019_Material002_0.geometry}
					material={gltf.materials['Material.002']}
				/>
				<T.Mesh
					castShadow
					receiveShadow
					geometry={gltf.nodes.Circle019_Material029_0.geometry}
					material={gltf.materials['Material.029']}
				/>
			</T.Group>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube_Building_0.geometry}
				material={gltf.materials.Building}
				position={[0, 100, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[-100.40287, 174.39224, 91.27816]}
				rotation={[0.56577, 0, 0]}
				scale={[4.66201, 4.56684, 4.56684]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle004_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[125.91895, 112.36591, 66.37627]}
				rotation={[Math.PI / 2, 1.17913, -Math.PI / 2]}
				scale={[4.66201, 2.62365, 2.85224]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle006_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[95.83088, 174.39224, -90.64381]}
				rotation={[2.57582, 0, Math.PI]}
				scale={[4.66201, 4.56684, 4.56684]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube002_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[0, 100, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert001_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[-105.96407, 237.74197, 3.18569]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle001_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[-89.9295, 112.36591, 107.11565]}
				rotation={[0.39166, 0, 0]}
				scale={[4.66201, 2.62365, 2.85224]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert003_Roof_Tiles_0.geometry}
				material={gltf.materials.Roof_Tiles}
				position={[-103.7373, 237.74197, -2.80579]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube015_Brown_0.geometry}
				material={gltf.materials.Brown}
				position={[-70.38, 62.22358, 79.90376]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube007_Material002_0.geometry}
				material={gltf.materials['Material.002']}
				position={[0, -3.73037, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube008_Material009_0.geometry}
				material={gltf.materials['Material.009']}
				position={[0, -3.73037, 0]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={100}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane_Red_0.geometry}
				material={gltf.materials.material}
				position={[4.60363, 18.29359, -4.30957]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[17.37607, 17.37607, 16.36119]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube010_Brown_0.geometry}
				material={gltf.materials.Brown}
				position={[4.41272, 35.5638, -66.50508]}
				rotation={[-Math.PI / 2, 0, -Math.PI]}
				scale={[-24.93481, 3.71719, 5.74935]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert007_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-2.49637, 20.32743, -0.22217]}
				rotation={[-Math.PI / 2, 0, 0.6399]}
				scale={[87.54533, 87.54533, 87.54534]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert006_Material017_0.geometry}
				material={gltf.materials['Material.017']}
				position={[-116.14452, 1.88876, 111.46616]}
				rotation={[-Math.PI / 2, 0, 0.6399]}
				scale={[184.90666, 184.90666, 184.90662]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane001_Brown_0.geometry}
				material={gltf.materials.Brown}
				position={[100, 174.81027, 0]}
				rotation={[-Math.PI / 2, Math.PI / 2, 0]}
				scale={4.71725}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane002_Brown_0.geometry}
				material={gltf.materials.Brown}
				position={[-100.46557, 174.81027, 0]}
				rotation={[-Math.PI / 2, Math.PI / 2, 0]}
				scale={4.71725}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube016_Red_0.geometry}
				material={gltf.materials.material}
				position={[63.37194, 21.62806, -70.52175]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[13.62029, 7.16612, 17.38287]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane003_Material011_0.geometry}
				material={gltf.materials['Material.011']}
				position={[5.21458, 134.24576, 104.74175]}
				scale={[43.74411, 16.51554, 12.50843]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane015_Material016_0.geometry}
				material={gltf.materials['Material.016']}
				position={[-159.62312, -33.65507, 81.9258]}
				rotation={[-1.78145, -0.71266, -0.67626]}
				scale={[-1.81013, 1.87217, 1.71383]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane004_Material016_0.geometry}
				material={gltf.materials['Material.016']}
				position={[-159.62312, -33.65507, 105.29033]}
				rotation={[-1.69777, 0.60693, 2.96936]}
				scale={[-1.2325, 1.27475, 1.16693]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane005_Material016_0.geometry}
				material={gltf.materials['Material.016']}
				position={[-159.62312, -33.65507, 52.81391]}
				rotation={[-1.17274, 0.73579, 2.03886]}
				scale={[-1.60655, 1.66161, 1.52108]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane006_Material016_0.geometry}
				material={gltf.materials['Material.016']}
				position={[-199.01944, -33.33716, 41.24137]}
				rotation={[-2.17062, 0.57952, -2.8003]}
				scale={[-1.36445, 1.57038, 1.22483]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane007_Material016_0.geometry}
				material={gltf.materials['Material.016']}
				position={[-181.47498, -33.33716, -43.18994]}
				rotation={[-1.61484, 0.80746, 2.64821]}
				scale={[-1.88499, 2.16949, 1.6921]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube009_Brown_0.geometry}
				material={gltf.materials.Brown}
				position={[-62.07854, 35.54422, -70.64442]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[16.73383, 18.97392, 18.97392]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cube020_Material009_0.geometry}
				material={gltf.materials['Material.009']}
				position={[-83.64265, 30.62582, 57.04315]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={12.46229}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle008_Red_0.geometry}
				material={gltf.materials.material}
				position={[33.32844, 5.24502, -5.20375]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[7.94342, 7.94342, 5.06869]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle009_Red_0.geometry}
				material={gltf.materials.material}
				position={[4.81007, 5.25094, 25.58514]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={[7.94342, 7.94342, 5.06869]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle010_Red_0.geometry}
				material={gltf.materials.material}
				position={[-26.62362, 5.50884, -1.31289]}
				rotation={[-Math.PI / 2, 0, 0.34479]}
				scale={[7.94342, 7.94342, 5.06869]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Plane010_Material026_0.geometry}
				material={gltf.materials['Material.026']}
				position={[0.55092, 5.26392, 1.10285]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={46.57151}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder001_Black_0.geometry}
				material={gltf.materials.Black}
				position={[12.45236, 22.79355, -11.58663]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={2.33044}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Cylinder002_Black_0.geometry}
				material={gltf.materials.Black}
				position={[8.85954, 22.79355, 6.92755]}
				rotation={[-Math.PI / 2, 0, 0.43452]}
				scale={2.33044}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle011_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-41.59373, 42.737, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-1.6939, 1.6939, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle012_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-83.30257, 42.737, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-1.6939, 1.6939, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle013_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-41.59373, 28.86529, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle014_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-83.30257, 28.86529, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle015_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-41.59373, 20.84528, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle016_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-83.30257, 20.84528, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle017_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-61.9809, 28.86529, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Circle018_Black_0.geometry}
				material={gltf.materials.Black}
				position={[-61.9809, 20.84528, -59.03202]}
				rotation={[-Math.PI, 0, 0]}
				scale={[-2.50301, 2.50301, 2.2593]}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert002__0.geometry}
				material={gltf.materials['Vert.002__0']}
				position={[-10.96011, 132.54506, 105.95132]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={15.24575}
			/>
			<T.Mesh
				castShadow
				receiveShadow
				geometry={gltf.nodes.Vert004__0.geometry}
				material={gltf.materials['Vert.002__0']}
				position={[20.26954, 133.01033, 106.09457]}
				rotation={[-Math.PI / 2, 0, 0]}
				scale={17.48726}
			/>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
