<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 .\porsche911.glb --transform
Author: Karol Miklas (https://sketchfab.com/karolmiklas)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/free-1975-porsche-911-930-turbo-8568d9d14a994b9cae59499f0dbed21e
Title: FREE 1975 Porsche 911 (930) Turbo
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('models/porsche911-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group rotation={[-Math.PI / 2, 0, 0]} scale={1} position={[0,0,0]}>
			<T.Group rotation={[Math.PI / 2, 0, 0]}>
				<!--Targa-->
				<T.Group position={[0, 0.47, 3.12]} rotation={[-2.83, 0, Math.PI]} scale={[1, 0.96, 1]}>
					<T.Mesh geometry={gltf.nodes.Object_4.geometry} material={gltf.materials['930_plastics']} />
					<T.Mesh geometry={gltf.nodes.Object_5.geometry} material={gltf.materials['930_stickers']} />
					<T.Mesh geometry={gltf.nodes.Object_6.geometry} material={gltf.materials.plate} />
				</T.Group>
				<!--Ruota 1-->
				<T.Group position={[-1.16, 0.56, -1.21]} rotation={[0.48, 0, 0]}>
					<T.Mesh geometry={gltf.nodes.Object_8.geometry} material={gltf.materials['930_rim']} />
					<T.Mesh geometry={gltf.nodes.Object_9.geometry} material={gltf.materials['930_tire']} />
				</T.Group>
				<!--Ruota 2-->
				<T.Group position={[-1.02, 0.56, 1.97]} rotation={[0.5, -0.29, 0.15]}>
					<T.Mesh geometry={gltf.nodes.Object_11.geometry} material={gltf.materials['930_rim']} />
					<T.Mesh geometry={gltf.nodes.Object_12.geometry} material={gltf.materials['930_tire']} />
				</T.Group>
				<!-- Fanali piccoli-->
				<T.Group position={[0.66, 0.48, 3.11]} rotation={[0.16, 0.1, -0.02]} scale={0.91}>
					<T.Mesh geometry={gltf.nodes.Object_44.geometry} material={gltf.materials['930_plastics']} />
					<T.Mesh geometry={gltf.nodes.Object_45.geometry} material={gltf.materials['930_chromes']} />
				</T.Group>
				<!--Scheletro 1-->
				<T.Group position={[0.01, 1.67, 0.65]} scale={0.06}>
					<T.Mesh geometry={gltf.nodes.Object_55.geometry} material={gltf.materials.black} />
					<T.Mesh geometry={gltf.nodes.Object_56.geometry} material={gltf.materials['930_plastics']} />
				</T.Group>
				<!--Scheletro 2-->
				<T.Group position={[0.79, 0.49, -2.38]} rotation={[-1.77, -0.01, -0.46]} scale={6.31}>
					<T.Mesh geometry={gltf.nodes.Object_58.geometry} material={gltf.materials['930_chromes']} />
					<T.Mesh geometry={gltf.nodes.Object_59.geometry} material={gltf.materials.black} />
				</T.Group>
				<!--Scheletro 3 -->
				<T.Group position={[0, 0.87, 2.92]} rotation={[0.46, 0, 0]} scale={0.03}>
					<T.Mesh geometry={gltf.nodes.Object_63.geometry} material={gltf.materials['930_plastics']} />
					<T.Mesh geometry={gltf.nodes.Object_64.geometry} material={gltf.materials['930_stickers']} />
				</T.Group>
				<T.Group position={[-0.25, 1.33, 1.32]} rotation={[0.58, 0.32, -0.01]} scale={0.01}>
					<T.Mesh geometry={gltf.nodes.Object_68.geometry} material={gltf.materials['930_plastics']} />
					<T.Mesh
						geometry={gltf.nodes.Object_70.geometry}
						material={gltf.materials['930_plastics']}
						position={[37.47, -1.97, 0.92]}
						rotation={[-2.95, -1.38, -2.99]}
						scale={[14.49, 9.23, 13.31]}
					/>
				</T.Group>
				<T.Group position={[0, 0.68, -2.62]} scale={[1, 0.96, 1]}>
					<T.Mesh geometry={gltf.nodes.Object_78.geometry} material={gltf.materials['930_plastics']} />
					<T.Mesh geometry={gltf.nodes.Object_79.geometry} material={gltf.materials['930_stickers']} />
					<T.Mesh geometry={gltf.nodes.Object_80.geometry} material={gltf.materials.plate} />
				</T.Group>
				<!--	Ruota 3 -->
				<T.Group position={[1.02, 0.56, 1.97]} rotation={[0.52, -0.28, 0.16]}>
					<T.Mesh geometry={gltf.nodes.Object_88.geometry} material={gltf.materials['930_rim']} />
					<T.Mesh geometry={gltf.nodes.Object_89.geometry} material={gltf.materials['930_tire']} />
				</T.Group>
				<!-- Ruota 4 -->
				<T.Group position={[1.16, 0.56, -1.21]} rotation={[0.48, 0, 0]} scale={[0.89, 0.94, 0.94]}>
					<T.Mesh geometry={gltf.nodes.Object_117.geometry} material={gltf.materials['930_rim']} />
					<T.Mesh geometry={gltf.nodes.Object_118.geometry} material={gltf.materials['930_tire']} />
				</T.Group>
				<T.Mesh geometry={gltf.nodes.Object_14.geometry} material={gltf.materials['930_stickers']} />
				<T.Mesh geometry={gltf.nodes.Object_16.geometry} material={gltf.materials['930_stickers']} />
				<T.Mesh geometry={gltf.nodes.Object_18.geometry} material={gltf.materials['930_stickers']} />
				<T.Mesh
					geometry={gltf.nodes.Object_20.geometry}
					material={gltf.materials['930_lights']}
					position={[0.7, 0.51, -2.53]}
					rotation={[0.04, -0.21, 0.01]}
					scale={0.24}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_22.geometry}
					material={gltf.materials['930_lights']}
					position={[0, 0.69, -2.1]}
				/>
				<!--	Body-->
				<T.Mesh geometry={gltf.nodes.Object_24.geometry} material={gltf.materials['930_lights']} />
				<T.Mesh geometry={gltf.nodes.Object_26.geometry} material={gltf.materials.glass} />
				<T.Mesh geometry={gltf.nodes.Object_28.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_30.geometry} material={gltf.materials.paint} />
				<T.Mesh geometry={gltf.nodes.Object_32.geometry} material={gltf.materials.coat} />
				<T.Mesh
					geometry={gltf.nodes.Object_34.geometry}
					material={gltf.materials['930_plastics']}
					position={[0.25, 1.33, 1.33]}
					rotation={[0.62, 0.44, -0.1]}
					scale={0.01}
				/>
				<T.Mesh geometry={gltf.nodes.Object_36.geometry} material={gltf.materials.glass} />
				<T.Mesh geometry={gltf.nodes.Object_38.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh
					geometry={gltf.nodes.Object_40.geometry}
					material={gltf.materials['930_chromes']}
					position={[0.7, 0.51, -2.53]}
					rotation={[0.04, -0.21, 0.01]}
					scale={0.24}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_42.geometry}
					material={gltf.materials['930_plastics']}
					position={[0.7, 0.51, -2.53]}
					rotation={[0.04, -0.21, 0.01]}
					scale={0.24}
				/>
				<T.Mesh geometry={gltf.nodes.Object_47.geometry} material={gltf.materials.glass} />
				<T.Mesh
					geometry={gltf.nodes.Object_49.geometry}
					material={gltf.materials['930_chromes']}
					position={[-1.01, 1.26, 1.5]}
					rotation={[0.05, 0, 0.05]}
					scale={0.01}
				/>
				<!--Light -->
				<T.Mesh geometry={gltf.nodes.Object_51.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_53.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh
					geometry={gltf.nodes.Object_61.geometry}
					material={gltf.materials['930_plastics']}
					position={[0, 0.98, -2.49]}
					rotation={[2.32, 0, -Math.PI]}
					scale={0.02}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_66.geometry}
					material={gltf.materials['930_chromes']}
					position={[0.01, 1.67, 0.65]}
					scale={0.06}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_72.geometry}
					material={gltf.materials['930_plastics']}
					position={[0.63, 1.55, -1.29]}
					rotation={[-0.35, 0.04, -0.1]}
					scale={[0.2, 0.13, 0.19]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_74.geometry}
					material={gltf.materials['930_plastics']}
					position={[0.67, 1.36, 1.11]}
					rotation={[0.07, -1.09, -0.48]}
					scale={[0.2, 0.13, 0.18]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_76.geometry}
					material={gltf.materials['930_plastics']}
					position={[0.32, 1.39, -1.83]}
					rotation={[-0.51, -0.83, -0.19]}
					scale={0.01}
				/>
				<T.Mesh geometry={gltf.nodes.Object_82.geometry} material={gltf.materials['930_plastics']} />
				<T.Mesh
					geometry={gltf.nodes.Object_84.geometry}
					material={gltf.materials['930_lights']}
					rotation={[0, -0.05, 0.15]}
					scale={[0.72, 0.82, 0.82]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_86.geometry}
					material={gltf.materials['930_chromes']}
					position={[0, 1.05, 1.38]}
					rotation={[0, -0.05, 0.15]}
					scale={[0.72, 0.82, 0.82]}
				/>
				<T.Mesh geometry={gltf.nodes.Object_91.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_93.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_95.geometry} material={gltf.materials['930_lights_refraction']} />
				<T.Mesh geometry={gltf.nodes.Object_97.geometry} material={gltf.materials['930_lights']} />
				<T.Mesh geometry={gltf.nodes.Object_99.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_101.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_103.geometry} material={gltf.materials['930_plastics']} />
				<T.Mesh geometry={gltf.nodes.Object_105.geometry} material={gltf.materials['930_plastics']} />
				<T.Mesh geometry={gltf.nodes.Object_107.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_109.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_111.geometry} material={gltf.materials['930_chromes']} />
				<T.Mesh geometry={gltf.nodes.Object_113.geometry} material={gltf.materials.paint} />
				<!--Body-->
				<T.Mesh
					geometry={gltf.nodes.Object_115.geometry}
					material={gltf.materials['930_chromes']}
					position={[1.08, 1.21, 0.93]}
					rotation={[0, 0, -0.06]}
					scale={0.93}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_120.geometry}
					material={gltf.materials['930_rim']}
					position={[1.02, 0.56, 1.97]}
					rotation={[0.52, -0.28, 0.16]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_122.geometry}
					material={gltf.materials['930_wunderbaum']}
					position={[0, 1.58, 0.67]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_124.geometry}
					material={gltf.materials['930_lights']}
					position={[0, 0.69, -2.1]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_126.geometry}
					material={gltf.materials['930_lights']}
					position={[-1.8, 0.14, 3.2]}
				/>
				<T.Mesh geometry={gltf.nodes.Object_128.geometry} material={gltf.materials.black} />
				<T.Mesh
					geometry={gltf.nodes.Object_130.geometry}
					material={gltf.materials['930_lights']}
					position={[0, 0.89, 4.01]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_132.geometry}
					material={gltf.materials['930_lights']}
					position={[0, 0.9, -3.5]}
				/>
				<T.Mesh
					geometry={gltf.nodes.Object_134.geometry}
					material={gltf.materials['930_lights']}
					position={[1.8, 0.14, 3.2]}
				/>
				<T.Mesh geometry={gltf.nodes.Object_136.geometry} material={gltf.materials['930_stickers']} />
				<T.Mesh geometry={gltf.nodes.Object_138.geometry} material={gltf.materials['930_stickers']} />
				<!--! Low light-->
				<!--				<T.Mesh-->
				<!--					geometry={gltf.nodes.Object_140.geometry}-->
				<!--					material={gltf.materials.material_0}-->
				<!--					position={[0, 0.14, 0.28]}-->
				<!--					scale={[1.92, 1.92, 3.84]}-->
				<!--				/>-->
			</T.Group>
		</T.Group>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
