<!--
Auto-generated by: https://github.com/threlte/threlte/tree/main/packages/gltf
Command: npx @threlte/gltf@2.0.3 sushi_set_japanese_harmony.glb --transform
Author: zxckurayami (https://sketchfab.com/zxckurayami)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/sushi-set-japanese-harmony-a3badb4e035a4cca8078b43402347d13
Title: Sushi set Japanese Harmony
-->

<script>
	import { Group } from 'three';
	import { T, forwardEventHandlers } from '@threlte/core';
	import { useGltf } from '@threlte/extras';

	export const ref = new Group();

	const gltf = useGltf('models/sushi_set_japanese_harmony-transformed.glb', { useDraco: true });

	const component = forwardEventHandlers();
</script>

<T is={ref} dispose={false} {...$$restProps} bind:this={$component}>
	{#await gltf}
		<slot name="fallback" />
	{:then gltf}
		<T.Group position={[1.86, 0.52, -4.1]} scale={0.49}>
			<T.Mesh geometry={gltf.nodes.Object_48.geometry} material={gltf.materials['.037']} />
			<T.Mesh geometry={gltf.nodes.Object_50.geometry} material={gltf.materials['.039']} />
		</T.Group>
		<T.Group position={[-3.12, 0.31, 0.47]} scale={0.3}>
			<T.Mesh geometry={gltf.nodes.Object_162.geometry} material={gltf.materials['.079']} />
			<T.Mesh geometry={gltf.nodes.Object_163.geometry} material={gltf.materials['.079']} />
			<T.Mesh geometry={gltf.nodes.Object_164.geometry} material={gltf.materials['.079']} />
			<T.Mesh geometry={gltf.nodes.Object_165.geometry} material={gltf.materials['.079']} />
		</T.Group>
		<T.Mesh
			geometry={gltf.nodes.Object_4.geometry}
			material={gltf.materials['.010']}
			position={[-2.03, 2.52, -4.17]}
			rotation={[0, 0.66, 0]}
			scale={2.11}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_6.geometry}
			material={gltf.materials['.003']}
			position={[-2.03, 0.41, -4.17]}
			rotation={[-Math.PI, 0.66, 0]}
			scale={[0.84, 0.97, 0.84]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_8.geometry}
			material={gltf.materials['.011']}
			position={[-2.23, 1.67, -5.21]}
			rotation={[-3.05, -1.37, -2.43]}
			scale={0.59}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_10.geometry}
			material={gltf.materials['.012']}
			position={[-2.24, 1.67, -5.2]}
			rotation={[-3.05, -1.37, 2.28]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_12.geometry}
			material={gltf.materials['.012']}
			position={[-1.37, 1.65, -4.86]}
			rotation={[-3.12, -0.61, 2.2]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_14.geometry}
			material={gltf.materials['.011']}
			position={[-1.36, 1.64, -4.86]}
			rotation={[-3.12, -0.61, -2.51]}
			scale={0.59}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_16.geometry}
			material={gltf.materials['.068']}
			position={[-1.16, 1.59, -4.08]}
			rotation={[-0.13, 0.86, 1.29]}
			scale={[0.08, 0.59, 0.08]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_18.geometry}
			material={gltf.materials['.068']}
			position={[-0.98, 1.56, -3.91]}
			rotation={[-0.21, 0.95, 1.53]}
			scale={[0.08, 0.59, 0.08]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_20.geometry}
			material={gltf.materials['.068']}
			position={[-1.06, 1.77, -3.99]}
			rotation={[-0.41, 1, 1.53]}
			scale={[0.08, 0.59, 0.08]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_22.geometry}
			material={gltf.materials['.069']}
			position={[-2.19, 1.07, -4.08]}
			scale={2.96}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_24.geometry}
			material={gltf.materials['.069']}
			position={[-2.19, 1.37, -3.74]}
			rotation={[-Math.PI, 0.94, -Math.PI]}
			scale={2.96}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_26.geometry}
			material={gltf.materials['.069']}
			position={[-2.43, 1.55, -4.22]}
			rotation={[0, -0.65, 0]}
			scale={2.96}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_28.geometry}
			material={gltf.materials['.070']}
			position={[-2.03, 2.11, -4.17]}
			scale={1.66}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_30.geometry}
			material={gltf.materials['.071']}
			position={[-1.7, 1.5, -4.48]}
			scale={[0.49, 0.8, 0.49]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_32.geometry}
			material={gltf.materials['.072']}
			position={[-1.72, 1.67, -4.44]}
			scale={[0.33, 0.54, 0.33]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_34.geometry}
			material={gltf.materials['.073']}
			position={[-0.23, 1.82, -4.52]}
			rotation={[1.54, -0.15, -0.24]}
			scale={[0.35, 0.56, 0.43]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_36.geometry}
			material={gltf.materials['.073']}
			position={[-0.2, 1.82, -3.78]}
			rotation={[1.59, -0.15, 0.15]}
			scale={[0.35, 0.56, 0.43]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_38.geometry}
			material={gltf.materials['.074']}
			position={[-0.2, 1.84, -3.78]}
			rotation={[1.59, -0.15, 0.15]}
			scale={[0.37, 0.21, 0.43]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_40.geometry}
			material={gltf.materials['.074']}
			position={[-0.27, 1.84, -4.7]}
			rotation={[1.54, -0.15, -0.24]}
			scale={[0.37, 0.19, 0.43]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_42.geometry}
			material={gltf.materials['.074']}
			position={[-0.18, 1.84, -4.34]}
			rotation={[1.54, -0.15, -0.24]}
			scale={[0.37, 0.19, 0.43]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_44.geometry}
			material={gltf.materials['.075']}
			position={[1.04, 0.33, -1.14]}
			rotation={[0, 0, Math.PI / 2]}
			scale={[0.09, 0.12, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_46.geometry}
			material={gltf.materials['.075']}
			position={[1.04, 0.33, -1.65]}
			rotation={[0, 0, Math.PI / 2]}
			scale={[0.09, 0.12, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_52.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.56, 5.19]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.41, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_54.geometry}
			material={gltf.materials['.025']}
			position={[0.03, 0.56, 5.32]}
			rotation={[-0.34, -0.76, -0.24]}
			scale={[0.4, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_56.geometry}
			material={gltf.materials['.025']}
			position={[-0.11, 0.56, 5.46]}
			rotation={[1.23, -0.32, 0.73]}
			scale={[0.41, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_58.geometry}
			material={gltf.materials['.025']}
			position={[0.14, 0.75, 5.2]}
			rotation={[1.71, 0.14, 0.78]}
			scale={[0.39, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_60.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.93, 5.19]}
			rotation={[2.66, 0.73, 0.33]}
			scale={[0.37, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_62.geometry}
			material={gltf.materials['.028']}
			position={[0.17, 0.84, 5.61]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.13, 0.19, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_64.geometry}
			material={gltf.materials.material}
			position={[0.02, 0.76, 5.33]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={0.53}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_66.geometry}
			material={gltf.materials['.017']}
			position={[0.02, 0.76, 5.33]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.26, 0.3, 0.3]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_68.geometry}
			material={gltf.materials['.001']}
			position={[1.73, 0.55, 5.29]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.82, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_70.geometry}
			material={gltf.materials['.007']}
			position={[1.74, 0.94, 5.3]}
			rotation={[0, Math.PI / 4, 0]}
			scale={[0.52, 0.04, 1.96]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_72.geometry}
			material={gltf.materials['.008']}
			position={[1.73, 0.78, 5.29]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.19, 0.42, 0.42]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_74.geometry}
			material={gltf.materials['.001']}
			position={[-1.56, 0.65, 5.33]}
			scale={[0.48, 0.46, 0.48]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_76.geometry}
			material={gltf.materials['.008']}
			position={[-1.56, 0.66, 5.34]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.51, 0.43, 0.51]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_78.geometry}
			material={gltf.materials['.001']}
			position={[0.02, 0.76, 5.33]}
			rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_80.geometry}
			material={gltf.materials['.004']}
			position={[-0.69, 0, 0]}
			scale={[3.67, 0.25, 6.47]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_82.geometry}
			material={gltf.materials['.004']}
			position={[-0.69, -0.69, -4.07]}
			rotation={[-Math.PI / 2, 0, 0]}
			scale={[3.65, 0.26, 0.62]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_84.geometry}
			material={gltf.materials['.008']}
			position={[1.73, 0.78, 3.79]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.19, 0.42, 0.42]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_86.geometry}
			material={gltf.materials['.007']}
			position={[1.74, 0.94, 3.8]}
			rotation={[0, Math.PI / 4, 0]}
			scale={[0.52, 0.04, 1.96]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_88.geometry}
			material={gltf.materials['.001']}
			position={[1.73, 0.55, 3.79]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.82, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_90.geometry}
			material={gltf.materials['.001']}
			position={[1.73, 0.55, 2.29]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.82, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_92.geometry}
			material={gltf.materials['.007']}
			position={[1.74, 0.94, 2.3]}
			rotation={[0, Math.PI / 4, 0]}
			scale={[0.52, 0.04, 1.96]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_94.geometry}
			material={gltf.materials['.008']}
			position={[1.73, 0.78, 2.29]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.19, 0.42, 0.42]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_96.geometry}
			material={gltf.materials['.001']}
			position={[1.73, 0.55, 0.79]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.82, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_98.geometry}
			material={gltf.materials['.007']}
			position={[1.74, 0.94, 0.8]}
			rotation={[0, Math.PI / 4, 0]}
			scale={[0.52, 0.04, 1.96]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_100.geometry}
			material={gltf.materials['.008']}
			position={[1.73, 0.78, 0.79]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.19, 0.42, 0.42]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_102.geometry}
			material={gltf.materials['.028']}
			position={[0.17, 0.84, 3.91]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.13, 0.19, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_104.geometry}
			material={gltf.materials.material}
			position={[0.02, 0.76, 3.63]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={0.53}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_106.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.93, 3.49]}
			rotation={[2.66, 0.73, 0.33]}
			scale={[0.37, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_108.geometry}
			material={gltf.materials['.025']}
			position={[0.14, 0.75, 3.5]}
			rotation={[1.71, 0.14, 0.78]}
			scale={[0.39, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_110.geometry}
			material={gltf.materials['.025']}
			position={[-0.11, 0.56, 3.76]}
			rotation={[1.23, -0.32, 0.73]}
			scale={[0.41, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_112.geometry}
			material={gltf.materials['.025']}
			position={[0.03, 0.56, 3.62]}
			rotation={[-0.34, -0.76, -0.24]}
			scale={[0.4, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_114.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.56, 3.49]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.41, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_116.geometry}
			material={gltf.materials['.001']}
			position={[0.02, 0.76, 3.63]}
			rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_118.geometry}
			material={gltf.materials['.017']}
			position={[0.02, 0.76, 3.63]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.26, 0.3, 0.3]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_120.geometry}
			material={gltf.materials['.028']}
			position={[0.17, 0.84, 2.21]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.13, 0.19, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_122.geometry}
			material={gltf.materials['.017']}
			position={[0.02, 0.76, 1.93]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.26, 0.3, 0.3]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_124.geometry}
			material={gltf.materials['.001']}
			position={[0.02, 0.76, 1.93]}
			rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_126.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.56, 1.79]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.41, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_128.geometry}
			material={gltf.materials['.025']}
			position={[0.03, 0.56, 1.92]}
			rotation={[-0.34, -0.76, -0.24]}
			scale={[0.4, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_130.geometry}
			material={gltf.materials['.025']}
			position={[-0.11, 0.56, 2.06]}
			rotation={[1.23, -0.32, 0.73]}
			scale={[0.41, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_132.geometry}
			material={gltf.materials['.025']}
			position={[0.14, 0.75, 1.8]}
			rotation={[1.71, 0.14, 0.78]}
			scale={[0.39, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_134.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.93, 1.79]}
			rotation={[2.66, 0.73, 0.33]}
			scale={[0.37, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_136.geometry}
			material={gltf.materials.material}
			position={[0.02, 0.76, 1.93]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={0.53}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_138.geometry}
			material={gltf.materials['.028']}
			position={[0.17, 0.84, 0.51]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.13, 0.19, 0.19]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_140.geometry}
			material={gltf.materials.material}
			position={[0.02, 0.76, 0.23]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={0.53}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_142.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.93, 0.09]}
			rotation={[2.66, 0.73, 0.33]}
			scale={[0.37, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_144.geometry}
			material={gltf.materials['.025']}
			position={[0.14, 0.75, 0.1]}
			rotation={[1.71, 0.14, 0.78]}
			scale={[0.39, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_146.geometry}
			material={gltf.materials['.025']}
			position={[-0.11, 0.56, 0.36]}
			rotation={[1.23, -0.32, 0.73]}
			scale={[0.41, 0.1, 0.1]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_148.geometry}
			material={gltf.materials['.025']}
			position={[0.03, 0.56, 0.22]}
			rotation={[-0.34, -0.76, -0.24]}
			scale={[0.4, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_150.geometry}
			material={gltf.materials['.025']}
			position={[0.16, 0.56, 0.09]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.41, 0.09, 0.09]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_152.geometry}
			material={gltf.materials['.001']}
			position={[0.02, 0.76, 0.23]}
			rotation={[-Math.PI, Math.PI / 4, -Math.PI]}
			scale={0.45}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_154.geometry}
			material={gltf.materials['.017']}
			position={[0.02, 0.76, 0.23]}
			rotation={[0, -Math.PI / 4, 0]}
			scale={[0.26, 0.3, 0.3]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_156.geometry}
			material={gltf.materials['.077']}
			position={[-3.12, 1.11, 4.6]}
			scale={[0.59, 0.88, 1.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_158.geometry}
			material={gltf.materials['.077']}
			position={[-3.12, 1.11, 1.1]}
			scale={[0.59, 0.88, 1.15]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_160.geometry}
			material={gltf.materials['.076']}
			position={[-3.12, 0.4, 4.6]}
			scale={[0.57, 0.16, 1.11]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_167.geometry}
			material={gltf.materials['.080']}
			position={[-3.22, 0.52, 1.55]}
			scale={[0.32, 0.56, 0.56]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_169.geometry}
			material={gltf.materials['.080']}
			position={[-3.22, 0.63, 1.55]}
			rotation={[0, 0.46, 0]}
			scale={[0.32, 0.56, 0.56]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_171.geometry}
			material={gltf.materials['.080']}
			position={[-3.22, 0.7, 1.55]}
			rotation={[0, -0.55, 0]}
			scale={[0.32, 0.56, 0.56]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_173.geometry}
			material={gltf.materials['.080']}
			position={[-3.14, 0.75, 1.58]}
			rotation={[0, 1.19, 0]}
			scale={[0.32, 0.56, 0.56]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_175.geometry}
			material={gltf.materials['.080']}
			position={[-3.07, 0.79, 1.58]}
			rotation={[-Math.PI, 0.89, -Math.PI]}
			scale={[0.32, 0.56, 0.56]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_177.geometry}
			material={gltf.materials['.077']}
			position={[1.8, 1.11, -4.09]}
			scale={[0.7, 0.88, 1.71]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_179.geometry}
			material={gltf.materials['.083']}
			position={[1.79, 0.4, -4.09]}
			scale={[0.69, 0.16, 1.67]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_181.geometry}
			material={gltf.materials['.018']}
			position={[-1.56, 0.92, 5.25]}
			rotation={[0, -Math.PI / 4, -1.56]}
			scale={[0.01, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_183.geometry}
			material={gltf.materials['.025']}
			position={[-1.72, 0.98, 5.5]}
			rotation={[2.49, -1.57, -2.18]}
			scale={[0.02, 0.2, 0.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_185.geometry}
			material={gltf.materials['.017']}
			position={[-1.56, 0.65, 5.34]}
			scale={0.33}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_187.geometry}
			material={gltf.materials['.008']}
			position={[-1.56, 0.66, 3.74]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.51, 0.43, 0.51]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_189.geometry}
			material={gltf.materials['.001']}
			position={[-1.56, 0.65, 3.73]}
			scale={[0.48, 0.46, 0.48]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_191.geometry}
			material={gltf.materials['.018']}
			position={[-1.56, 0.92, 3.65]}
			rotation={[0, -Math.PI / 4, -1.56]}
			scale={[0.01, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_193.geometry}
			material={gltf.materials['.017']}
			position={[-1.56, 0.65, 3.74]}
			scale={0.33}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_195.geometry}
			material={gltf.materials['.025']}
			position={[-1.72, 0.98, 3.9]}
			rotation={[2.49, -1.57, -2.18]}
			scale={[0.02, 0.2, 0.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_197.geometry}
			material={gltf.materials['.001']}
			position={[-1.56, 0.65, 2.13]}
			scale={[0.48, 0.46, 0.48]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_199.geometry}
			material={gltf.materials['.008']}
			position={[-1.56, 0.66, 2.14]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.51, 0.43, 0.51]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_201.geometry}
			material={gltf.materials['.018']}
			position={[-1.56, 0.92, 2.05]}
			rotation={[0, -Math.PI / 4, -1.56]}
			scale={[0.01, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_203.geometry}
			material={gltf.materials['.025']}
			position={[-1.72, 0.98, 2.3]}
			rotation={[2.49, -1.57, -2.18]}
			scale={[0.02, 0.2, 0.18]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_205.geometry}
			material={gltf.materials['.017']}
			position={[-1.56, 0.65, 2.14]}
			scale={0.33}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_207.geometry}
			material={gltf.materials['.008']}
			position={[-1.56, 0.66, 0.54]}
			rotation={[-Math.PI, 0, -Math.PI]}
			scale={[0.51, 0.43, 0.51]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_209.geometry}
			material={gltf.materials['.001']}
			position={[-1.56, 0.65, 0.53]}
			scale={[0.48, 0.46, 0.48]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_211.geometry}
			material={gltf.materials['.018']}
			position={[-1.56, 0.92, 0.45]}
			rotation={[0, -Math.PI / 4, -1.56]}
			scale={[0.01, 0.36, 0.36]}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_213.geometry}
			material={gltf.materials['.017']}
			position={[-1.56, 0.65, 0.54]}
			scale={0.33}
		/>
		<T.Mesh
			geometry={gltf.nodes.Object_215.geometry}
			material={gltf.materials['.025']}
			position={[-1.72, 0.98, 0.7]}
			rotation={[2.49, -1.57, -2.18]}
			scale={[0.02, 0.2, 0.18]}
		/>
	{:catch error}
		<slot name="error" {error} />
	{/await}

	<slot {ref} />
</T>
